export const LIST = "PUBLICATIONS_LIST";
export const PER_USER = "PUBLICATIONS_PER_USER";
export const LOADING = "PUBLICATIONS_LOADING";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const ERROR = "PUBLICATIONS_ERROR";
export const ERROR_COMMENTS = "ERROR_COMMENTS";

